name       : doflicky
version    : '6'
release    : 13
source     :
    - https://github.com/solus-project/doflicky/archive/v6.tar.gz : d77876516011cba4cee79723cec300d7db686e86621b7b309717041e5ce729ca
license    : GPL-2.0
component  : system.utils
summary    : Solus Driver Management
description: |
    A tool to provide automated driver detection and management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - nvidia-304-glx-driver-modaliases
    - nvidia-340-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Fixed-a-comparison-where-the-wrong-driver-will-be-di.patch
build      : |
    %python_setup
install    : |
    %python_install
    chmod 00644 $installdir/usr/share/applications/*.desktop -v
