name       : doflicky
version    : 5
release    : 8
source     :
    - https://github.com/solus-project/doflicky/releases/download/v5/doflicky-5.tar.gz : 7d52e62479262d268dbb48a2b7778afb9b73f5dd25aab2f0741874e88266ef25
license    : GPL-2.0
summary    : Solus Driver Management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
component  : desktop.budgie
rundeps    :
    - nvidia-304-glx-driver-modaliases
    - nvidia-340-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
description: |
    A tool to provide automated driver detection and management
build      : |
    %python_setup
install    : |
    %python_install
