name       : doflicky
version    : 5
release    : 10
source     :
    - https://github.com/solus-project/doflicky/releases/download/v5/doflicky-5.tar.gz : 7d52e62479262d268dbb48a2b7778afb9b73f5dd25aab2f0741874e88266ef25
license    : GPL-2.0
component  : system.utils
summary    : Solus Driver Management
description: |
    A tool to provide automated driver detection and management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - nvidia-304-glx-driver-modaliases
    - nvidia-340-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-doflicky-Fix-broken-signal-name.patch
build      : |
    %python_setup
install    : |
    %python_install
