name       : doflicky
version    : 4
release    : 7
source     :
    - https://github.com/solus-project/doflicky/releases/download/v4/doflicky-4.tar.gz : 5e54a75f82d0d7e609dd3572792357db2b14f1003db7934dad20b4d7c25db33a
license    : GPL-2.0
summary    : Solus Driver Management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
component  : desktop.budgie
rundeps    :
    - nvidia-304-glx-driver-modaliases
    - nvidia-340-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
description: |
    A tool to provide automated driver detection and management
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-discoverability-for-MATE-desktop.patch
    %patch -p1 < $pkgfiles/0002-Ensure-we-show-in-both-MATE-Budgie.patch
build      : |
    %python_setup
install    : |
    %python_install
