name       : doflicky
version    : 2
release    : 3
source     :
    - https://github.com/solus-project/doflicky/archive/v2.tar.gz : 46bd7c4b4f5d9f9f17306054e5ed66ddfd684a4090c3c9cef2259875bb9896e8
license    : GPL-2.0
summary    : Solus Driver Management
rundeps    :
    - nvidia-304-glx-driver-modaliases
    - nvidia-340-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
description: |
    A tool to provide automated driver detection and management
install    : |
    install -D -m 00755 main.py $installdir/usr/bin/doflicky
    install -D -d -m 00755 $installdir/usr/share/doflicky/doflicky
    for i in doflicky/*.py ; do
        install -m 00644 $i $installdir/usr/share/doflicky/doflicky/.
    done
    install -D -m 00644 doflicky.desktop $installdir/usr/share/applications/doflicky.desktop
