name       : doflicky
version    : '6'
release    : 19
source     :
    - git|https://github.com/getsolus/doflicky.git : 9142ee365e61e614cfe9a503f717316c23c5c28d
license    : GPL-2.0-only
component  : system.utils
summary    : Solus Driver Management
description: |
    A tool to provide automated driver detection and management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - nvidia-390-glx-driver-modaliases
    - nvidia-470-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/nvidia_470.patch
build      : |
    %python_setup
install    : |
    %python_install
    chmod 00644 $installdir/usr/share/applications/*.desktop -v
