name       : doflicky
version    : '6'
release    : 20
source     :
    - git|https://github.com/getsolus/doflicky.git : 5c4a0dbb83cdef50e5e7f1e4bfbe3ef16485821b
license    : GPL-2.0-only
component  : system.utils
summary    : Solus Driver Management
description: |
    A tool to provide automated driver detection and management
builddeps  :
    - pkgconfig(python-2.7)
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - nvidia-470-glx-driver-modaliases
    - nvidia-glx-driver-modaliases
    - python-gobject
build      : |
    %python_setup
install    : |
    %python_install
    chmod 00644 $installdir/usr/share/applications/*.desktop -v
